Task6
natali-maximenko/ruby-basics pull request #1
Opened 2017-04-06 04:56 UTC by natali-maximenko

2017-04-06 10:05 UTC, zverok requested changes
Часть замечаний к коду, который в PR не попал, поэтому здесь. 

1. Хорошо бы чтобы «какого класса создать фильм» решал специальный метод-фабрика в Movie, чтобы коллекция могла просто сказать `Movie.create(row)`
2. А как ж, для классического фильма «...ещё N фильмов этого режиссёра в топе»? ;)

2017-04-06 10:05 UTC, zverok commented on movie.rb
>    end
a) Лучше `#{@title}`, такое упрощение плохо читается и его обычно избегают, как ни странно
б) можно (и здесь и для остальных фильмов) не выносить куски в переменные, `"#@title - latest, was released #{Date.today.year - @year} years ago!"` читается вполне прилично (особенно если ты году сделаешь `.to_i` в конструкторе)

2017-04-06 10:05 UTC, zverok commented on movie.rb
>    end
`@period = :new` (и в других фильмах тоже) совершенно не нужно, у тебя же все объекты этого класса имеют одно и то же значение, так? Поэтому достаточно
```ruby
def period
  :new
end
```
...а не заполнять отдельно переменную. (Ну или можно повыделываться и в базовом классе `Movie` определить метод `period`, который будет его выводить из имени текущего класса, и поэтому в каждом наследнике возвращать своё.)

2017-04-06 10:05 UTC, zverok commented on movie_collection.rb
> +    super(filename)
Кстати, если вызвать `super` просто без скобок и аргументов — ему сами передадутся все аргументы текущего метода ;)

2017-04-06 10:05 UTC, zverok commented on movie_collection.rb
> +    payment = {ancient: 1, classic: 1.5, modern: 3, new: 5}
По-моему это хочет быть константой.

2017-04-06 10:05 UTC, zverok commented on movie_collection_spec.rb
> +  end
Смотри, как можно:
```ruby
let(:netflix) { Netflix.new('movies.txt') } # штука, которая будет использоваться в куче тестов
describe '#pay' do # опишем поведение метода pay
  it 'updates account' do # мы проверяем, что этот метод меняет аккаунт!
    expect { netflix.pay(25) }.to change(netflix, :account).from(0).to(25)
  end

  it 'fails on negative amounts' do
    expect { netflix.pay(-5) }.to raise_error ....
  end
end
```

То есть надо почитать http://betterspecs.org/ (обязательно на английском, русская версия не обновляется!) и разделить все тесты на:
* что тестируем (let и subject)
* какие поведения тестируем — когда и как должно сработать, как должно сломаться.

2017-04-06 10:05 UTC, zverok commented on movie_collection_spec.rb
> +      netflix = Netflix.new('movies.txt')
`let`. Потому что с `let` переменная инициируется при каждом прогоне теста, а вот таким образом — только один раз, когда тест определяется (соответственно, если ты в этот блок поместишь пяток тестов, они будут влиять друг на друга, получая уже изменённый `netflix`)

2017-04-06 16:54 UTC, natali-maximenko commented on movie_collection.rb
> +    super(filename)
чудеса)

2017-04-07 12:34 UTC, zverok commented on movie_collection_spec.rb
> +      expect { netflix.pay(-5) }.to raise_error
Лучше проверять, какую именно (а то может у тебя там просто опечатка, и прилетает ошибка типа NameError, а не «извините так платить нельзя»)

2017-04-07 12:57 UTC, zverok commented on movie_collection.rb
> +    raise NegativeAmount if amount < 0
а) лучше бы использовать ArgumentError или её наследника в этом контексте
б) вообще не стоит увлекаться своими классами ошибок, они нужны когда мы ожидаем что клиентский код захочет поймать именно такую ошибку, а начинать всегда лучше со стандартных классов, но с осмысленным описанием, типа `raise ArgumentError, "Amount should be positive, #{amount} passed"`

2017-04-10 16:09 UTC, zverok requested changes
Смысл пойман, но много-много мелочей (и не очень мелочей) ещё надо разобрать.

2017-04-10 16:09 UTC, zverok commented on movie.rb
> +    end
После `raise` — `else` уже не нужен (если `if` сработал, до этой строчки дело всё равно не дойдёт)

2017-04-10 16:09 UTC, zverok commented on movie_collection.rb
> +    film = filtered.first
По-моему из этих двух вполне получится одна строчка.

2017-04-10 16:09 UTC, zverok commented on movie_collection.rb
> +class Netflix < MovieCollection
Мы обычно кладём каждый класс в свой файл. Это не жёсткое правило (например, маленькие классы-наследники Movie можно оставить с ним), но более-менее общепринятое. И ревьювить легче ;)

2017-04-10 16:09 UTC, zverok commented on movie_collection.rb
> +    movies = case daytime
Стоит попытаться использовать константу `DAYTIME`. А то у тебя получается что в двух независимых местах есть данные о том, как выбираются фильмы в зависимости от времени. (Подсказка: небольшое усложнение `Movie#match?` может помочь)

2017-04-10 16:09 UTC, zverok commented on movie_collection.rb
> +    if movie.match?(:period, :ancient)
Опять же, стоит использовать ту же константу. Представь, что пришёл директор кинотеатра и просит поменять фильтры. Чем больше в коде раз «спрятаны» эти данные, тем сложнее будет эта задача!
Хороший код — это код, который легко изменить.

2017-04-10 16:09 UTC, zverok commented on movie_collection_spec.rb
> +describe Netflix do
А вот спеки для разных классов точно лучше по разным файлам разложить.

2017-04-10 16:09 UTC, zverok commented on demo.rb
> +filtered.each {|movie| movie.load_collection(movies) }
То есть если «клиентский» код этого не сделает, всё сломается? Нехорошо :(
Мне кажется, лучше пусть оно в конструктор передаётся (всем фильмам, те классы которым оно нужно — используют)

2017-04-10 16:09 UTC, zverok commented on movie.rb
> +    "<AncientMovie title: '#{@title}', year: #{@year}, country: #{@country}, date: #{@date}, genre: '#{@genre}', length: #{@length}, rating: #{@rating}, director: '#{@director}', actors: '#{@actors}'
Если ты решила пойти таким путём (у всех фильмов `inspect` одинаковый кроме названия класса) — так наверное имеет смысл его сделать в базовом `Movie`? Просто подставив название класса через `self.class.name`

2017-04-10 16:09 UTC, zverok commented on movie_collection_spec.rb
> +    end
Лучше из этого сделать три `context`. Тогда ты сможешь выделить «сколько у нас есть денег» в отдельный `let`, оплату этих денег — в `before`, и тест будет тестировать именно «что произошло».

2017-04-10 16:09 UTC, zverok commented on movie_collection_spec.rb
> +    end
Лучше `each_pair` вынести снаружу, чтобы получилась куча тестов:
```ruby
Netflix::PRICES.each_pair do |period, price|
  context "when movie from #{period} period" do
    let(:title) { netflix.filter(period: period).first.title }
    subject { netflix.how_much?(title) }
    it { is_expected.to eq price }
  end
end
```

Проверь в формате `rspec --format doc`, как выглядят твой и предложенный варианты.

2017-04-10 16:09 UTC, zverok commented on movie_spec.rb
>  end
А как насчёт спек на `Movie.create`, они у нас есть?

2017-04-12 17:33 UTC, zverok requested changes
Давай, чтобы уже всё в порядок положенный пришло, разложим файлы по папкам (кстати, в процессе require_relative должен бы помочь):
* классы и модули в lib/, 
* спеки в spec/
* демку в bin/demo.rb или examples/demo.rb

...и обсудим оставшиеся мелочи. Их осталось немного :)

2017-04-12 17:33 UTC, zverok commented on movie_collection.rb
> +    puts "Now showing: #{movie.title}" + start_time.strftime(" %I:%M%p") + end_time.strftime(" - %I:%M%p")
Это уже придирки по мелочам, но лучше не смешивать водной строки интерполяцию и суммирование строк. Для такого сложного случая вообще может иметь смысл написать вот так:
```ruby
"Now showing %s (%s-%s)" % [movie.title, start_time.strftime("%I:%M%p"), end_time.strftime("%I:%M%p")]
```
(что кстати позволяет формат времени, который теперь стал одинаковым, выложить в константу, и теперь будет видно как всё происходит)

2017-04-12 17:33 UTC, zverok commented on movie_spec.rb
> +      subject { Movie.create(movie) }
это можно вынести выше (в `describe '#create'`), будет актуально для всех контекстов внутри.

2017-04-12 17:33 UTC, zverok commented on movie_spec.rb
> +      end
`it { is_expected.to be_an(AncientMovie) }` ;)

2017-04-12 17:33 UTC, zverok commented on movie_spec.rb
> +  let(:collection) { MovieCollection.new('movies.txt') }
По хорошему, чтобы протестировать тут честно `ClassicMovie` и только его, вместо коллекции осмысленно использовать `double`, её имитирующий ;) Так мы опишем, что ожидается именно от этого класса (и что он ожидает от окружающих)

2017-04-12 19:59 UTC, natali-maximenko commented on movie_spec.rb
> +  let(:collection) { MovieCollection.new('movies.txt') }
что-то у меня проблемы с осмысленным использованием double коллекции) 
`describe ClassicMovie do
  let(:collection) { instance_double(MovieCollection) }
  let(:info) { ['http://imdb.com/title/tt0053291/?ref_=chttp_tt_111','Some Like It Hot','1959','USA','1959-03-29','Comedy','120 min','8.3','Billy Wilder','Marilyn Monroe,Tony Curtis,Jack Lemmon', collection] }
  let(:movie) { ClassicMovie.new(*info) }
  it 'return movie description' do
    expect(collection).to receive(:filter).with({director: 'Billy Wilder'})
    expect(movie.to_s).to eq('Some Like It Hot - classic movie, director Billy Wilder (5 movies in top-250)')
  end
end`

т.е. я поняла что double должен имитировать экземпляр класса, мы можем проверить через receive вызов методов имитируемого класса, видимо на этом понимание кончается, дубль же заполнить нужно как-то, чтобы я могла с ним, как с коллекцией взаимодействовать

2017-04-13 10:26 UTC, zverok commented on lib/movie.rb
> +  end
По-моему этот метод уже не нужен?

2017-04-13 10:26 UTC, zverok commented on movie_spec.rb
> +  let(:collection) { MovieCollection.new('movies.txt') }
Заполнять его полностью совершенно не нужно :) Смотри, тут всё просто:
```ruby
before { expect(collection).to receive(:filter).with(director: 'Billy Wilder').and_return(double(size: 5)) }
its(:to_s) { is_expected to.... }
```
Что декларирует код выше? Что 
а) для генерации своего строкового представления, фильм будет использовать метод `filter`
б) ...и что у результата этого `filter` ему интересен только `size`, он его вставит в описание

Всё, задача решена!

2017-04-13 10:56 UTC, zverok requested changes
Довольно близко уже к неплохим спекам! Но есть несколько важных замечаний + не игнорируй последнее задание («усложнение»), оно добавит пару интересных challenges в тестирование этого всего.

2017-04-13 10:56 UTC, zverok commented on spec/movie_spec.rb
> +  end
Хороший принцип тестирования всего — проверить, что будет если аргументы за пределами ожидаемых значений ;) Ну, так, к слову. Конечно, не стоит тестировать абсолютно все варианты, но учитывая что фильмы читаются из CSV, и там легко могут перепутаться поля, и `'some garbage'.to_i == 0`, стоит проверить что мы выбросим красивую ошибку (или что-то другое осмысленное сделаем).

2017-04-13 10:56 UTC, zverok commented on spec/movie_spec.rb
> +  end
На самом деле тут можно срезать (с вышесоветованным гемом `rspec-its`) — просто написать `its(:to_s) { is_expected.to eq .... }` — это будет уже достаточно неплохо документировать, что происходит.

Секрет в том, что чем короче тесты (без потери понятности) — тем менее лень их писать :)

2017-04-13 10:56 UTC, zverok commented on spec/netflix_spec.rb
> +      subject { netflix.show(classic_comedies) }
subject всё ещё повторяется, положи его в строчку 19 (он сам будет правильно определяться в разных контекстах)

2017-04-13 10:56 UTC, zverok commented on spec/netflix_spec.rb
> +          expect { subject }.to output(message).to_stdout
Я кажется писал уже — здесь можно сделать просто вот так:
```ruby
expect { subject }.to output("Now showing: Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb - 7:30 - 8:40")
```
Плюсы:
а) читателю тестов будет сразу видно, чего ты пыталась добиться (ну и тебе будет это сразу видно)
б) учитывая, что сейчас у тебя код одинаковый и там и там (в коде и в тесте) — в нём может быть один и тот же баг (например что-то выводится очень некрасиво, с тремя лишними пробелами, но это незаметно за сложной логикой конструирования ожидаемого мессиджа)

2017-04-13 10:56 UTC, zverok commented on spec/netflix_spec.rb
> +    end
А если не найдена киношка?

2017-04-13 10:56 UTC, zverok commented on spec/theatre_spec.rb
> +    end
Давай-ка знаешь что сделаем? Пусть зритель передаёт «в котором часу», а не `:morning`, `:evening` и т.д. Зрителю-то невдомёк, как кинотеатр для себя отделяет «день от утра», его вопрос выглядит как «что идёт сейчас?» или «что бы мне посмотреть после работы?»

2017-04-13 10:56 UTC, zverok commented on spec/theatre_spec.rb
> +      expect { theatre.show(:morning) }.to output(message).to_stdout
Опять же те же соображения про «что должно вывести»

2017-04-13 19:35 UTC, natali-maximenko commented on movie_spec.rb
> +  let(:collection) { MovieCollection.new('movies.txt') }
что-то всё равно не доходит, before задаст какого мы поведения ожидаем, а сам дубль как правильно задать?
`let(:collection) { instance_double(MovieCollection) }`
`subject { ClassicMovie.new('http://imdb.com/title/tt0053291/?ref_=chttp_tt_111','Some Like It Hot','1959','USA','1959-03-29','Comedy','120 min','8.3','Billy Wilder','Marilyn Monroe,Tony Curtis,Jack Lemmon', collection) }`
` before { expect(collection).to receive(:filter).with(director: 'Billy Wilder').and_return(double(size: 5)) }`
`its(:to_s) { is_expected.to eq('Some Like It Hot - classic movie, director Billy Wilder (5 movies in top-250)') }`
выдаёт 

> 1) ClassicMovie to_s should receive filter({:director=>"Billy Wilder"}) 1 time
     Failure/Error: movies = @collection.filter(director: @director).count
       #<Double (anonymous)> received unexpected message :count with (no args)

2017-04-13 19:36 UTC, natali-maximenko commented on spec/movie_spec.rb
> +  end
проверку добавила и в тест тоже

2017-04-13 19:36 UTC, natali-maximenko commented on spec/movie_spec.rb
> +  end
исправила, действительно в разы короче)

2017-04-13 19:36 UTC, natali-maximenko commented on spec/netflix_spec.rb
> +      subject { netflix.show(classic_comedies) }
переселила, не повторяется

2017-04-13 19:38 UTC, natali-maximenko commented on spec/netflix_spec.rb
> +          expect { subject }.to output(message).to_stdout
вопрос: у меня в тексте сообщение считается время от текущего момента, т.е. я не могу в тесте угадать что там за цифра должна быть (она меняется постоянно), перемудрила с функционалом? сделать начало в 10 утра, конец через длительность фильма?

2017-04-13 19:39 UTC, natali-maximenko commented on spec/netflix_spec.rb
> +    end
переделала, проверка на наличие киношки в контексте, который выше

2017-04-13 19:39 UTC, natali-maximenko commented on spec/theatre_spec.rb
> +      expect { theatre.show(:morning) }.to output(message).to_stdout
тот же вопрос про текущее значение времени

2017-04-13 21:17 UTC, zverok commented on spec/netflix_spec.rb
> +          expect { subject }.to output(message).to_stdout
если у нас что-то от «текущего момента» — то пригодится библиотека timecop, которая позволяет сказать тестировать штуки работающие со временем, сказав «давай для этого теста заморозим время на 10:30, и протестируем, что будет»

2017-04-14 12:18 UTC, natali-maximenko commented on spec/netflix_spec.rb
> +          expect { subject }.to output(message).to_stdout
какая крутая штука!

2017-04-14 12:21 UTC, natali-maximenko commented on spec/theatre_spec.rb
> +      expect { theatre.show(:morning) }.to output(message).to_stdout
решился с timecop

2017-04-15 08:35 UTC, zverok commented on spec/netflix_spec.rb
> +          expect { subject }.to output(message).to_stdout
(кстати, рекомендации на свободное время/на потом — разбираться, как такие крутые штуки сделаны и работают. или придумывать, как бы ты это сделала сама ;) В руби это довольно легко, как ни странно, вся библиотека timecop не слишком «умная», просто одна хорошая идея превращённая в библиотеку)

2017-04-16 20:00 UTC, natali-maximenko commented on spec/theatre_spec.rb
> +    end
сделала

2017-04-17 17:14 UTC, zverok approved these changes

2017-04-17 17:17 UTC, merged