task9
natali-maximenko/ruby-basics pull request #4
Opened 2017-04-27 08:58 UTC by natali-maximenko

2017-04-27 17:22 UTC, zverok requested changes

2017-04-27 17:22 UTC, zverok commented on lib/movie.rb
> +    attribute :actors, String
Но ведь актёры и жанры у нас — массив строк! Надо научить Виртуса это понимать.

2017-04-28 08:46 UTC, natali-maximenko commented on lib/movie.rb
> +    attribute :actors, String
сделала

2017-05-02 15:45 UTC, zverok commented on lib/collection_by_country.rb
> +      end
Можно чуть компактнее сделать, если почитать доки на `fetch` — он позволяет указать, что делать если не найден ключ:
```ruby
@countries.fetch(m) { raise ArgumentError, 'country not exist in collection' }
```
(Но даже без этой фичи, лучше было бы сначала проверить наличие ключа и сразу бросить ошибку — а тогда уже продолжить нормальное выполнение.)

2017-05-02 15:47 UTC, zverok commented on lib/collection_by_country.rb
> +    end
Ещё пара вещей про method_missing:
а) хорошо бы проверять, что нам не передали аргументов и блоков, т.е. что никто не пытается сделать что-то вроде `collection.by_countries.usa(false)` (неважно, что он себе думал, но очевидно что мы должны ему показать, что он делает что-то неожиданное)
б) при определении `method_missing` прилично рядом определять `respond_to_missing?` — чтобы продолжалась логика обычных методов, для которых если можно сказать `object.something`, значит `object.respond_to?(:something)` будет `true`.

2017-05-02 15:49 UTC, zverok commented on lib/netflix.rb
> +      CollectionByGenre.new(self)
Лучше закешировать (в смысле `@by_genre ||=`), а то сто раз кто-то вызовет `by_genre` — сто раз будет объект создаваться, жанры вытаскиваться и т.д.

2017-05-02 15:52 UTC, zverok reviewed
Вообще очень качественный код, я доволен :+1:

2017-05-02 18:22 UTC, natali-maximenko commented on lib/collection_by_country.rb
> +      end
ага, никак не избавлюсь в голове от конструкций if-else

2017-05-02 18:22 UTC, natali-maximenko commented on lib/netflix.rb
> +      CollectionByGenre.new(self)
логично)

2017-05-02 18:47 UTC, natali-maximenko commented on lib/collection_by_country.rb
> +    end
сделала, надеюсь, что правильно поняла

2017-05-08 19:05 UTC, zverok requested changes
Хорошо бы на CustomSchedule отдельные тесты, вне рамок кинотеатров и DSL. Это поможет его отдизайнить независимым и аккуратным.

2017-05-08 19:05 UTC, zverok commented on lib/custom_schedule.rb
> +    end
Смотри, с этим методом интересно. По сути, на обычном человеческом языке это звучит так: «для всех заданных расписаний показа фильма, проверить, не пересекаются ли они в одном и том же зале». То есть, переводя это на Руби, в принципе может быть что-то типа (это воображаемый код)
```ruby
def valid?
  !@periods.combination(2).any? { |p1, p2| p1.intersect?(p2) }
end
```
...этот код сразу остановится после первого пересечения, и полагается на то, как внутри класса `Period` определено пересечение двух периодов, м?

2017-05-11 10:33 UTC, natali-maximenko commented on lib/custom_schedule.rb
> +    end
переделала

2017-05-11 12:34 UTC, zverok requested changes
Вообще всё норм уже :) Оставил немношк всяких советов.

2017-05-11 12:34 UTC, zverok commented on lib/hall.rb
> +  end
Теоретически, эти классы не видны и не нужны никому кроме CustomSchedule, их можно сложить внутрь него (и даже прямо в том же файле), читабельнее будет.

2017-05-11 12:34 UTC, zverok commented on lib/period.rb
> +end
А, впрочем этот класс таки большой, в тот же файл что Schedule его класть не надо, пожалуй :)

2017-05-11 12:34 UTC, zverok commented on lib/schedule_builder.rb
> +  end
В принципе, в таком виде он не очень нужен, этот же метод можно просто в Theatre запихать. Подход с builder, который я имел в виду (но я на нём не настаиваю) вот такой (только для CustomSchedule):
```ruby
class Builder
  def initialize(&block)
    @schedule = CustomSchedule.new
    instance_eval(&block) # на себе, а не на Custom
  end

  def hall(...)
    @schedule.halls << .......
  end
end
# или даже лучше
class Builder
  def initialize(&block)
    @halls = []
    @periods = []
    instance_eval(&block) # на себе, а не на Custom
    @schedule = CustomSchedule.new(halls: @halls, periods: @periods)
  end

  def hall(...)
    @halls << .......
  end
end
```

Идея такого подхода (когда он полезен), что отдельно у тебя есть простой CustomSchedule, который просто можно создать — только не очень удобно (придётся писать `CustomSchedule.new(halls: [Hall.new(...), Hall.new(...).....`), использовать и протестировать. А отдельно есть Builder, который обеспечивает DSL создания.

2017-05-11 12:34 UTC, zverok commented on lib/period.rb
> +    end
Вот на эту штуку лучше бы отдельных тестов, тут алгоритм умеренно сложный и легко ошибиться.

2017-05-15 08:10 UTC, natali-maximenko commented on lib/hall.rb
> +  end
Hall перенесла в файл c CustomSchedule

2017-05-15 08:11 UTC, natali-maximenko commented on lib/period.rb
> +end
я тоже так думаю)

2017-05-15 08:32 UTC, natali-maximenko commented on lib/schedule_builder.rb
> +  end
просто создание расписания перенесла в theatre#initialize, а про билдер ещё спрошу

2017-05-15 10:50 UTC, natali-maximenko commented on lib/period.rb
> +    end
ага

2017-05-15 15:51 UTC, merged