task10
natali-maximenko/ruby-basics pull request #5
Opened 2017-05-16 20:34 UTC by natali-maximenko

2017-05-21 17:59 UTC, zverok requested changes

2017-05-21 17:59 UTC, zverok commented on lib/movie.rb
> +    attribute :id, String, :default => lambda { |movie, attribute| movie.link.split('/')[4] }
```ruby
default: ->(movie, attribute) { movie.link.split('/')[4] }
```

2017-05-21 17:59 UTC, zverok commented on lib/movie.rb
> +    attribute :budget, String, :default => nil
`default: nil`

2017-05-21 17:59 UTC, zverok commented on lib/movie_scraper.rb
> +      end
Это чтобы что?..

2017-05-21 17:59 UTC, zverok commented on lib/movie_scraper.rb
> +      if (!File.exist?("#{TMP_DIR}/#{id}"))
Заметь, что это повторяет проверку в строке 28. Я бы сделал только одну проверку, прям в этом  методе, как-то так:
1. если файл существует, вернуть его содержимое сразу
2. если нет — прочитать из сети и сохранить, и вернуть содержимое прочитанного

м?

2017-05-21 17:59 UTC, zverok commented on lib/movie_scraper.rb
> +        end
`File.write('...', open(url).read)` м?

2017-05-21 17:59 UTC, zverok commented on spec/movie_scraper_spec.rb
> +    end
Тест, который каждый раз лезет в интернет — это плохо! Тебе нужен webmock (и вероятно vcr) — которые я смотрю в spec_helper подключены, но тут не используются?.. позволяющие имитировать запросы в интернет для тестирования.

И, по сути, вся история про тестирование кеша — она скорее должна выглядеть так:
1. «кеш существует»: `before` создаём кеш-файл, в самом тесте тестируем `not_requested(some_url)`, `after` удаляем файл
2. «кеша не существует»: в самом тесте тестируем `have_requested(url)`

2017-05-21 18:49 UTC, natali-maximenko commented on lib/movie.rb
> +    attribute :id, String, :default => lambda { |movie, attribute| movie.link.split('/')[4] }
ага

2017-05-21 18:49 UTC, natali-maximenko commented on lib/movie.rb
> +    attribute :budget, String, :default => nil
ага

2017-05-22 10:20 UTC, natali-maximenko commented on lib/movie_scraper.rb
> +      if (!File.exist?("#{TMP_DIR}/#{id}"))
логично, исправила

2017-05-22 12:44 UTC, natali-maximenko commented on lib/movie_scraper.rb
> +        end
ага

2017-05-22 12:47 UTC, natali-maximenko commented on spec/movie_scraper_spec.rb
> +    end
в интернет при тестах мы не ходим, spec_helper подключен в movie_scraper_spec  и пишет запросы в spec/vcr

2017-05-22 12:49 UTC, natali-maximenko commented on spec/movie_scraper_spec.rb
> +    end
я её просто не стала в гит заливать, потому что она рабочая

2017-05-22 15:01 UTC, zverok requested changes
Вообще, конечно, на _этом_ уровне уже можно говорить, скажем так, на равных: в том смысле, что можно поспорить про некоторые решения, но во многом это уже вопрос личного вкуса. Поэтому я оставил комменты только про самое важное.

2017-05-22 15:01 UTC, zverok commented on lib/movie_scraper.rb
> +    TMDB_KEY = '374ec1b6307d5583ba7e0805836077aa'
Это, кстати, превесьма нехорошо — хранить ключи в коде, надо сразу избавляться от такой привычки :)
А если это ключ от коммерческого сервиса/сервиса с жёсткими ограничениями на использование, а все вокруг твой ключ начнут использовать?

Обычные подходы:
* хранить в `config/something.yml`, при этом не сохранять его в .git, а в .git хранить `config/something.yml.samle`
* хранить в environment variables, при этом гем dotenv позволяет загружать их для тестирования из `.env` (его конечно тоже нужно в .gitignore)

2017-05-22 15:01 UTC, zverok commented on spec/movie_collection_spec.rb
> +      it { expect(movies.last.year).to eq(2015) }
К слову (ну это мелочи, но всё же) наверное здесь можно как-то вот так:
```ruby
it { is_expected.to all have_attributes(year: 1921..2015) }
```
или что-то в этом роде.

2017-05-22 15:01 UTC, zverok commented on spec/spec_helper.rb
> +  end
Да, теперь понял. Я не знаю, где ты взяла эту идею (или просто придумала?), она остроумна, но мне кажется что это довольно дурной тон. Потому что на самом деле добавлять VCR автоматом и невидимо везде — это пример bad magic. Прямо из коробки VCR позволяет делать так:
```ruby
describe Something, :vcr do
# вот тут VCR активен
end
# или в одном-единственном контексте...
context 'when loaded from internetz', :vcr do
# ...
end
```
— и это позволяет читателю тестов обратить внимание, что вот ЭТА спека таки собралась лезть в интернет, обрати внимание.

2017-05-22 17:47 UTC, natali-maximenko commented on lib/movie_scraper.rb
> +    TMDB_KEY = '374ec1b6307d5583ba7e0805836077aa'
поленилась делать конфиг, но раз один раз поленилась - не факт, что это не повторится) переделала

2017-05-22 17:52 UTC, natali-maximenko commented on spec/movie_collection_spec.rb
> +      it { expect(movies.last.year).to eq(2015) }
ага

2017-05-22 18:37 UTC, natali-maximenko commented on spec/spec_helper.rb
> +  end
что-то VCR у меня из коробки как-то никак не заводился, отсюда и эта чёрная магия, сейчас разобралась

2017-05-22 20:29 UTC, zverok approved these changes

2017-05-22 20:37 UTC, merged