task11
natali-maximenko/ruby-basics pull request #6
Opened 2017-05-25 08:59 UTC by natali-maximenko

2017-05-25 15:21 UTC, zverok requested changes
Ага, едем дальше.

2017-05-27 13:52 UTC, zverok commented on lib/cinema.rb
> +require 'cinema/movie_scraper'
обычно в этом же главном файле определяют пустой модуль `Cinema` — так сразу видно, куда будет сложено всё остальное + к нему тут можно и доки написать (ну если мы пишем доки для всего, в смысле это взрослый гем)

2017-05-27 13:56 UTC, zverok commented on lib/cinema/movie_collection.rb
> +    # @note if attribute is [Integer] you may pass [Range] in value
Я бы здесь написал что-то вроде "Attributes checking is performed with `===`, so you can pass ranges, regexps and other generic patterns". Более информативно.

2017-05-27 13:57 UTC, zverok commented on lib/cinema/movie_collection.rb
>      def most_popular_movie(collection)
к слову, этот метод наверное имеет смысл сделать приватным, он же для внутренних только целей?.. и соответственно можно не документировать.

2017-05-27 14:03 UTC, zverok commented on lib/cinema/movie_collection.rb
>    class MovieCollection
Вообще (ну это на будущее, я не думаю что это сейчас необходимо), главная дока должна быть здесь — что это за класс, зачем он нужен, как используется и т.п.

Доки — в некотором смысле другая разновидность спек, пока их пишешь (= объясняя, что это такое и зачем нужно) — лучше понимаешь, всё ли тут понятно и логично, или какой-то функционал явно не вписывается, или непохож на то как другой функционал выглядит.

Я пару раз уже почти совсем готовый гем начинал документировать и в процессе переделывал пол-архитектуры, чтобы понятнее было :)

2017-05-27 14:05 UTC, zverok commented on spec/movie_spec.rb
> +require 'spec_helper'
Можно (точнее нужно) написать файл `.rspec`, в котором это всё происходит (подключение хелпера в частности)

2017-05-27 14:05 UTC, zverok commented on spec/netflix_spec.rb
>  require 'money'
Кажется все эти `require` тут лишние :)

2017-05-27 14:11 UTC, zverok commented on cinema.gemspec
> +end
Зависимости! Идея в том, что если поставить эту штуку на чистый компьютер, все её `require` должны работать — то есть все гемы, которые используются в `lib` (money, tmdb, nokogiri) должны установиться вместе с твоей либой

2017-05-27 15:58 UTC, natali-maximenko commented on lib/cinema.rb
> +require 'cinema/movie_scraper'
ага

2017-05-27 15:59 UTC, natali-maximenko commented on lib/cinema/movie_collection.rb
> +    # @note if attribute is [Integer] you may pass [Range] in value
ага

2017-05-27 16:00 UTC, natali-maximenko commented on lib/cinema/movie_collection.rb
>      def most_popular_movie(collection)
ага

2017-05-27 16:01 UTC, natali-maximenko commented on lib/cinema/movie_collection.rb
>    class MovieCollection
учту)

2017-05-27 16:10 UTC, natali-maximenko commented on spec/movie_spec.rb
> +require 'spec_helper'
ага

2017-05-27 16:16 UTC, natali-maximenko commented on spec/netflix_spec.rb
>  require 'money'
ага

2017-05-27 16:25 UTC, natali-maximenko commented on cinema.gemspec
> +end
ага

2017-05-27 16:25 UTC, natali-maximenko commented on spec/movie_spec.rb
> +require 'spec_helper'
он у меня есть, я его просто в gem files не включила

2017-05-27 17:31 UTC, zverok commented on spec/movie_spec.rb
> +require 'spec_helper'
так тогда можно прям в нём прописать `--require ./spec/spec_helper` и не надо будет в каждом файле вписывать.

2017-05-27 17:37 UTC, natali-maximenko commented on spec/movie_spec.rb
> +require 'spec_helper'
уже прописала, см последний коммит

2017-05-27 18:50 UTC, zverok commented on cinema.gemspec
> +  s.add_development_dependency 'themoviedb-api'
"development dependency" — это то, что устанавливается при разработке.
А то, что нужно во время просто работы гема — это «runtime dependency»
Если бы это был настоящий гем, то `gem install cinema` не установил бы money, virtus, nokogiri — и гем бы не работал.

2017-05-27 19:46 UTC, natali-maximenko commented on cinema.gemspec
> +  s.add_development_dependency 'themoviedb-api'
прошляпила

2017-05-28 15:49 UTC, zverok approved these changes

2017-05-28 15:54 UTC, merged